# Generated by Django 2.1.7 on 2019-03-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verified',
        ),
    ]
