# Generated by Django 2.1.7 on 2019-03-30 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_user', '0004_auto_20190330_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersessions',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 19, 29, 32, 88832)),
        ),
    ]
