# Generated by Django 2.1.7 on 2019-04-02 17:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb_user', '0005_auto_20190330_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=200)),
                ('expired_at', models.DateTimeField(default=datetime.datetime(2019, 5, 2, 17, 58, 43, 700430))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersessions',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserSessions',
        ),
    ]
