# Generated by Django 2.1.7 on 2019-04-04 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_user', '0007_auto_20190404_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 14, 1, 12, 936058)),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
