# Generated by Django 2.1.7 on 2019-04-04 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_user', '0009_auto_20190404_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 14, 5, 3, 68220)),
        ),
    ]
