# Generated by Django 2.1.7 on 2019-04-04 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_user', '0013_auto_20190404_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 17, 40, 27, 668145)),
        ),
    ]
