# Generated by Django 2.1.7 on 2019-04-04 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_user', '0014_auto_20190404_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_reset_token',
            new_name='password_reset',
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 17, 42, 28, 515494)),
        ),
    ]
