# Generated by Django 2.1.7 on 2019-04-05 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_user', '0015_auto_20190404_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 5, 7, 38, 54, 269197)),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=True),
        ),
    ]
