# Generated by Django 2.1.7 on 2019-04-08 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_user', '0016_auto_20190405_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 17, 12, 25, 660576)),
        ),
    ]
