# Generated by Django 2.1.7 on 2019-04-08 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_user', '0017_auto_20190408_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 17, 15, 44, 693760)),
        ),
    ]
